apiVersion: v2
name: pocket-id
description: A Helm chart for Pocket ID
type: application
version: 0.0.0
appVersion: "v2.9.0"
keywords:
  - oidc
  - authentication
  - passkey
  - identity
home: https://pocket-id.org
sources:
  - https://github.com/pocket-id/pocket-id
