apiVersion: v2
name: pocket-id
description: A Helm chart for Pocket ID
type: application
version: 1.0.3
appVersion: "latest"
keywords:
  - oidc
  - authentication
  - passkey
  - identity
home: https://pocket-id.org
sources:
  - https://github.com/pocket-id/pocket-id
