name: Lint

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  helm-lint:
    name: Helm Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Set up Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2  # v5.0.0

      - name: Lint chart
        run: helm lint .

      - name: Validate rendered templates
        run: helm template pocket-id . > /dev/null
